global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets:
#       - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing endpoints to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mongodb_monitoring'
    scrape_interval: 15s
    static_configs:
      - targets: ['mongodb-monitoring:8000']

  - job_name: 'redis_celery_monitoring'
    scrape_interval: 15s
    static_configs:
      - targets: ['redis-celery-monitoring:8001']

  # Add more monitoring targets as needed
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100'] 